[package]
name = "fnvcli"
version = "0.1.0"
authors = ["artemetra <artemlukin15@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
clap = { version = "4.6.7", features = ["derive"] }
anyhow = "1.0.104"
log = "0.4.34"
nom = "8.0.0"
